---
- name: Install packages
  apt: name={{ item }} state=present
  with_items: packages

- name: Start MySQL service
  service: name=mysql state=started enabled=true

- name: Create database users
  mysql_user: name={{ item.name }} password={{ item.name }} priv={{ item.name }}.*:ALL,GRANT state=present
  with_items: databases

- name: Create databases
  mysql_db: name={{ item.name }} state=present
  with_items: databases

- name: Import data
  shell: /usr/bin/mysql -u{{ item.name }} -p{{ item.name }} {{ item.name }} < /vagrant/sql/{{ item.name }}.sql creates={{ item.creates }}
  with_items: databases